Add const folding for float add and sub
insufficiently-caffeinated/caffeine pull request #132
Opened 2021-01-20 18:07 UTC by mishazharov

This PR is 1/2 for implementing constant folding for floating point expressions.

Part of #96

2021-01-20 18:16 UTC, mishazharov commented on src/Interpreter/CtxConstEval.cpp
> +#undef BINARY_NAN_PROPAGATE
This is optional since the macros are in a source file but I thought it was nice anyway

2021-01-20 18:45 UTC, Phantomical commented
Shouldn't this be changing the `CreateXXX` functions in Operation.cpp? Constant folding is also needed outside of evaluating globals

2021-01-20 20:55 UTC, mishazharov commented
> Shouldn't this be changing the `CreateXXX` functions in Operation.cpp? Constant folding is also needed outside of evaluating globals.

Yup I flubbed it. Will fix

2021-01-23 04:16 UTC, Phantomical requested changes
One last thing: it's basically never correct to convert an APFloat back to a float or double for calculation purposes since that'll give wrong values for other float sizes (what about fp80 or fp128?)

2021-01-23 04:16 UTC, Phantomical commented on src/IR/Operation.cpp
> +        fmod(lhs_float->value().convertToFloat(),
This doesn't work if the value stored in the APFloat isn't a float. Isn't there a method on APFloat to do this properly?

2021-01-23 17:55 UTC, Phantomical approved these changes
Approved provided that you fix the last two comments :)

2021-01-23 17:55 UTC, Phantomical commented on src/IR/Operation.h
> +    return lhs.compare(rhs) != llvm::APFloat::cmpGreaterThan;
Isn't this backwards? Shouldn't it be `lhs.compare(rhs) == llvm::APFloat::cmpGreaterThan`?

2021-01-23 17:55 UTC, Phantomical commented on src/IR/Operation.h
> +    return lhs.compare(rhs) != llvm::APFloat::cmpLessThan;
Same thing here.

2021-01-23 18:12 UTC, mishazharov commented on src/IR/Operation.h
> +    return lhs.compare(rhs) != llvm::APFloat::cmpGreaterThan;
Nice catch, copy pasta strikes again

2021-01-23 18:16 UTC, merged