Add const lookup to Context
insufficiently-caffeinated/caffeine pull request #152
Opened 2021-01-25 20:40 UTC by mishazharov

This PR adds a `const` `lookup` method to `Context` which is necessary for #92 in order to check values in the `FailureHandler`

2021-01-25 20:46 UTC, mishazharov commented on include/caffeine/Interpreter/CtxConstEval.h
> +static std::optional<ContextValue> evaluate_expr(ContextParamTy ctx,
Mostly copy pasted from `CtxConstEval.cpp` with macro changes

2021-01-25 20:46 UTC, mishazharov commented on cmake/testutils.cmake
> +
vscode got rid of some whitespace so ¯\\_(ツ)_/¯

2021-01-25 20:46 UTC, mishazharov commented on src/bin/caffeine.cpp
> +    }
Empty lookups which do nothing right now

2021-01-26 00:09 UTC, Phantomical requested changes
Lots of comments here, sorry. I think the general approach is right but there's some issues:
- Can you move `evaluate_expr` back into `CtxConstEval.cpp`. It's an internal helper function that shouldn't be accessible to external users and moving it makes the diff much harder to review (IMO) unnecessarily.
- Some of the other helpers also need to be turned into templates, I've marked which ones I noted would need this.
- Having const and non-const overloads of a function that do slightly different things (beyond just const/non-const) is quite easy to screw up for users of the API. Maybe rename the constant overloads to distinguish them? The const overloads also need docs to explain what they're doing and how they're different from the non-const ones.

In short - the functionality looks correct (+/- some template overload issues). Most of my issues here are around code layout and naming.

2021-01-26 00:09 UTC, Phantomical commented on include/caffeine/Interpreter/Context.h
>     * modify the registered globals table.
I think we need a second set of docs for the `const` version of `evaluate_constant` to communicate just how it differs.

Since it actually has different behaviour I think it's worth putting it under a different name? It's going to be really confusing to use this API since the const and non-const perform similar, but not quite the same, operations.

2021-01-26 00:09 UTC, Phantomical commented on include/caffeine/Interpreter/Context.h
> +  std::optional<ContextValue> lookup(llvm::Value* value) const;
Same comment as below (on both counts). Maybe `lookup_const` would work as a name?

2021-01-27 06:58 UTC, mishazharov commented on src/Interpreter/CtxConstEval.cpp
> +  *evaluate(ctx, llvm::cast<llvm::Constant>((expr)->getOperand(num)))
This is a bug since the optional result isn't checked and is just dereferenced right away

2021-01-27 23:50 UTC, Phantomical approved these changes
One thing left. LGTM otherwise!

2021-01-27 23:50 UTC, Phantomical commented on src/bin/caffeine.cpp
>    using caffeine::PrintingFailureLogger::PrintingFailureLogger;
You'll want to remove this. If CountingFailureLogger is constructed with the inherited constructor then `func` won't get initialized.

2021-01-28 02:21 UTC, merged