Add z3 solver struture
insufficiently-caffeinated/caffeine pull request #19
Opened 2020-11-20 01:45 UTC by Skrinikov

This is a WIP PR to see whether this is on the right track

2020-11-20 02:14 UTC, Phantomical reviewed
It looks like you're on the right track :) Left a few comments on things that looked fishy but that's it.

2020-11-20 02:14 UTC, Phantomical commented on include/caffeine/Solver/Z3Solver.h
> +#include "Solver.h"
Nit: this should probably be 
```
#include "caffeine/IR/Solver.h"
```
to be consistent.

2020-11-20 02:14 UTC, Phantomical commented on include/caffeine/Solver/Z3Solver.h
> +  z3::expr visitConstant     (Constant& op);
Unless I've messed something up, for `ConstOpVisitor` these should take const references (`const Constant& op`).

I suspect you'd find that once you try to run this none of the visit methods would be called.

2020-11-20 02:14 UTC, Phantomical commented on include/caffeine/Solver/Z3Solver.h
> +  ref<Operation> evaluate(const ref<Operation>& expr) const;
I should have a PR up tonight that implements a general `evaluate` so you can probably avoid implementing this for now.

2020-11-20 02:14 UTC, Phantomical commented on src/Solver/Z3Solver.cpp
> +  return ctx->fpa_val(op.value().convertToFloat()); // TODO: Is this corret?
We'll have to figure out a more general way to do this. It should be good enough for now but when we merge this we should open an issue to resolve it.

2020-11-20 15:56 UTC, Skrinikov commented on src/Solver/Z3Solver.cpp
> +CAFFEINE_OP_IMPL_DELEGATE(FAdd, lhs + rhs) // I did not see specific functions for floats?
At least in z3

2020-12-02 03:10 UTC, Phantomical requested changes
There's a few easily fixed but major problems. I've marked those.

Anything else we run into can be fixed later.

2020-12-02 03:10 UTC, Phantomical commented on src/Solver/Z3Solver.cpp
> +    CAFFEINE_ASSERT(false, "Unknown ICmpOpcode");
nit: You can just use `CAFFEINE_ABORT` here

2020-12-02 03:10 UTC, Phantomical commented on src/Solver/Z3Solver.cpp
> +Value Z3Model::evaluate(const ref<Operation>& expr) const {
You don't need to implement this. It's already implemented for the base `Model` class (and what you have here is wrong since it doesn't evaluate expression trees).

2020-12-02 03:10 UTC, Phantomical commented on include/caffeine/Solver/Z3Solver.h
> +  std::map<std::string, z3::expr*>& constMap;
Z3 expressions are reference counted so you can avoid the pointer here.

2020-12-02 03:10 UTC, Phantomical commented on src/Solver/Z3Solver.cpp
> +      return Value(llvm::APInt(32, result.get_numeral_int()));
Use the bitwidth of the type here (either from the z3 sort or from the constant type)

2020-12-02 03:10 UTC, Phantomical commented on src/Solver/Z3Solver.cpp
> +    return Value(llvm::APInt(32, it->second->get_numeral_int()));
Same comment about bitwidth here.

2020-12-02 03:10 UTC, Phantomical commented on src/Solver/Z3Solver.cpp
> +      return Value(); // I cant find the way to extract fpa
Yeah we can solve this in a follow-up PR.

2020-12-02 03:10 UTC, Phantomical commented on include/caffeine/Solver/Z3Solver.h
> +  std::map<std::string, z3::expr*> constants;
Same note here WRT to `z3::expr` and pointers.

2020-12-02 03:43 UTC, Phantomical approved these changes

2020-12-02 03:48 UTC, merged