Attempt to add multithreading
insufficiently-caffeinated/caffeine pull request #277
Opened 2021-03-28 05:54 UTC by mishazharov

Currently failing because move constructing a `MemHeap` fails (according to TSAN):

```
ThreadSanitizer:DEADLYSIGNAL
==10244==ERROR: ThreadSanitizer: SEGV on unknown address 0x000000001048 (pc 0x7f4ae89ac386 bp 0x000000001048 sp 0x7f4ae65bdaa0 T10245)
==10244==The signal is caused by a READ memory access.
    #0 <null> <null> (libtsan.so.0+0x89386)
    #1 <null> <null> (libtsan.so.0+0x87319)
    #2 <null> <null> (libtsan.so.0+0x87447)
    #3 malloc <null> (libtsan.so.0+0x30351)
    #4 <null> <null> (ld-linux-x86-64.so.2+0xfc39)
    #5 <null> <null> (ld-linux-x86-64.so.2+0x15d9f)
    #6 _dl_catch_exception <null> (libc.so.6+0x1638b7)
    #7 <null> <null> (ld-linux-x86-64.so.2+0x155f9)
    #8 <null> <null> (libc.so.6+0x162860)
    #9 _dl_catch_exception <null> (libc.so.6+0x1638b7)
    #10 _dl_catch_error <null> (libc.so.6+0x163982)
    #11 __libc_dlopen_mode <null> (libc.so.6+0x162994)
    #12 <null> <null> (libc.so.6+0x130048)
    #13 __pthread_once_slow /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_once.c:116 (libpthread.so.0+0x1247e)
    #14 __backtrace <null> (libc.so.6+0x130193)
    #15 __interceptor_backtrace <null> (libtsan.so.0+0x3f983)
    #16 llvm::sys::PrintStackTrace(llvm::raw_ostream&) <null> (caffeine+0x41702e)
    #17 llvm::sys::RunSignalHandlers() <null> (caffeine+0x4152df)
    #18 SignalHandler(int) <null> (caffeine+0x417574)
    #19 <null> <null> (libpthread.so.0+0x153bf)
    #20 <null> <null> (libtsan.so.0+0x89385)
    #21 <null> <null> (libtsan.so.0+0x87319)
    #22 <null> <null> (libtsan.so.0+0x87447)
    #23 operator new(unsigned long) <null> (libtsan.so.0+0x8c023)
    #24 __gnu_cxx::new_allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor*>::allocate(unsigned long, void const*) <null> (caffeine+0xdc49d)
    #25 std::allocator_traits<std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor*> >::allocate(std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor*>&, unsigned long) <null> (caffeine+0xdac0a)
    #26 std::_Deque_base<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >::_M_allocate_map(unsigned long) <null> (caffeine+0xd969d)
    #27 std::_Deque_base<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >::_M_initialize_map(unsigned long) <null> (caffeine+0xd7b7f)
    #28 std::_Deque_base<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >::_Deque_base(std::_Deque_base<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >&&, std::integral_constant<bool, true>) <null> (caffeine+0xe2d9c)
    #29 std::_Deque_base<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >::_Deque_base(std::_Deque_base<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >&&) <null> (caffeine+0xe24fa)
    #30 std::deque<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >::deque(std::deque<caffeine::slot_map<caffeine::Allocation>::with_dtor, std::allocator<caffeine::slot_map<caffeine::Allocation>::with_dtor> >&&) <null> (caffeine+0xe1dc9)
    #31 caffeine::slot_map<caffeine::Allocation>::slot_map(caffeine::slot_map<caffeine::Allocation>&&) <null> (caffeine+0xe18f5)
    #32 caffeine::MemHeap::MemHeap(caffeine::MemHeap&&) <null> (caffeine+0xe1940)
    #33 caffeine::Context::Context(caffeine::Context&&) <null> (caffeine+0xe1a0f)
    #34 void std::__invoke_impl<void, void (*)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*>(std::__invoke_other, void (*&&)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*&&, caffeine::Context&&, caffeine::FailureLogger*&&, boost::interprocess::interprocess_semaphore*&&) <null> (caffeine+0xe422f)
    #35 std::__invoke_result<void (*)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*>::type std::__invoke<void (*)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*>(void (*&&)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*&&, caffeine::Context&&, caffeine::FailureLogger*&&, boost::interprocess::interprocess_semaphore*&&) <null> (caffeine+0xe4091)
    #36 void std::thread::_Invoker<std::tuple<void (*)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) <null> (caffeine+0xe3f30)
    #37 std::thread::_Invoker<std::tuple<void (*)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*> >::operator()() <null> (caffeine+0xe3e93)
    #38 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*), caffeine::Executor*, caffeine::Context, caffeine::FailureLogger*, boost::interprocess::interprocess_semaphore*> > >::_M_run() <null> (caffeine+0xe3e73)
    #39 <null> <null> (libstdc++.so.6+0xd6d83)
    #40 start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477 (libpthread.so.0+0x9608)
    #41 __clone <null> (libc.so.6+0x122292)

ThreadSanitizer can not provide additional info.
SUMMARY: ThreadSanitizer: SEGV (/lib/x86_64-linux-gnu/libtsan.so.0+0x89386) 
==10244==ABORTING
<end of output>
```

2021-03-28 18:20 UTC, Phantomical requested changes
Here's my general suggestions:
- I'd recommend not using interprocess versions of semaphores for intra-process synchronization. The intra-process ones will be more efficient since they can take advantage of more OS funtionality.
- Please just create threads at startup and have them all basically run Executor::run. I'd suggest changing `next_context` to return a `std::optional<Context>` and to also be blocking. That way you can structure the main loop of `Executor::run` like this:
  ```cpp
  while (auto ctx = next_context()) {
    ...
  }
  ```
  I suspect that this would also fix your TSAN issue.

There's a few other bits around unnecessary locks that should be fixed.

2021-03-28 18:20 UTC, Phantomical commented on include/caffeine/Interpreter/Executor.h
> +#include <boost/interprocess/sync/interprocess_semaphore.hpp>
I imagine an interprocess semaphore is going to be less efficient then a normal one. Maybe use [`boost::sync::semaphore`](https://www.boost.org/doc/libs/develop/libs/sync/doc/html/boost/sync/semaphore.html) instead?

2021-03-28 18:20 UTC, Phantomical commented on src/Interpreter/Executor.cpp
> +    auto thread = std::thread(run_single_context, this, std::move(ctx), logger,
Do we really need to spawn a thread for every context? Why not start off by spawning n threads and have each of them keep checking for contexts until there's a global signal to shut down?

2021-03-28 18:20 UTC, Phantomical commented on src/Interpreter/PrintingFailureLogger.cpp
> +  std::unique_lock lock(mtx);
Why do we need the lock here? Could you print to a stringstream and then only hold the lock when writing the message to stdout.

2021-03-28 18:20 UTC, Phantomical commented on src/Interpreter/Executor.cpp
>      auto ctx = next_context();
My guess as to the TSAN issue you're seeing here is that access to the queue isn't being synchronized here.

2021-03-30 04:18 UTC, mishazharov commented on include/caffeine/Interpreter/Executor.h
> +#include <boost/interprocess/sync/interprocess_semaphore.hpp>
That primitive isn't actually in boost yet, but the other approach you suggested makes it possible to remove it.

2021-04-03 18:51 UTC, Phantomical approved these changes
Some small comments but LGTM otherwise

2021-04-03 18:51 UTC, Phantomical commented on src/Interpreter/Executor.cpp
> +    }
Nit: You can simplify this to
```suggestion
while (auto ctx = store->next_context()) {
```

2021-04-03 18:51 UTC, Phantomical commented on src/bin/caffeine.cpp
>        // TODO: Update once we actually support multithreaded execution
Remove the TODO?
```suggestion
```

2021-04-03 18:51 UTC, Phantomical commented on src/Interpreter/Executor.cpp
> +#include <iostream>
`iostream` doesn't appear to be used?
```suggestion
```
We should really set up a lint for this :)

2021-04-03 18:55 UTC, Phantomical commented on README.md
> +CC=clang-10 CXX=clang++-10 cmake -DCMAKE_C_FLAGS='-fsanitize=thread' -DCMAKE_CXX_FLAGS='-fsanitize=thread' ..
One last thing, maybe write this in terms of #303? (I realize this was added after you committed this)
```suggestion
CC=clang-10 CXX=clang++-10 cmake -DCAFFEINE_ENABLE_TSAN=ON ..
```

2021-04-03 19:20 UTC, merged