`Invoke` instruction implementation
insufficiently-caffeinated/caffeine pull request #480
Opened 2021-07-26 21:36 UTC by mishazharov

This PR allows us to symbolically execute c++ code which never throws exceptions.

2021-07-26 21:40 UTC, mishazharov commented on src/Interpreter/Interpreter.cpp
> +    return res;
This is the cruftiest part of the PR because:
1. Each `Invoke` instruction instance does not necessarily have a matching `Return` since these external functions are handled by Caffeine. As a result, I threw a `performInvokeReturn` at the end here to fix that
2. Maybe I could also template this instead so that we have a compile time check for whether this is an `Invoke` instruction instead of a runtime one

2021-07-26 22:24 UTC, Phantomical reviewed
This generally looks good to me but I think the `perfomInvokeReturn` logic doesn't work for non-standard control flow. Could you fix that?

2021-07-26 22:24 UTC, Phantomical commented on src/Interpreter/Interpreter.cpp
> +    return res;
This will break if any builtin function does a non-standard return (e.g. `longjmp`). I think to make this work you need to check that the current instruction has not been changed.

Could you also add a test case for this? Just one where you invoke a function and then `longjmp` away should enough to see whether this breaks.

2021-07-27 00:25 UTC, mishazharov commented on src/Interpreter/Interpreter.cpp
> +  performInvokeReturn(call);
wait this is wrong, the forks also need `performInvokeReturn`

2021-07-27 00:25 UTC, mishazharov commented on src/Interpreter/Interpreter.cpp
> +  performInvokeReturn(call);
need to do the same with the forks

2021-07-27 00:44 UTC, Phantomical commented on src/Interpreter/Interpreter.cpp
> +  performInvokeReturn(call);
You can probably ignore this since `resolve` will never be called by outside functions. Up to you

2021-07-27 00:48 UTC, mishazharov commented on src/Interpreter/Interpreter.cpp
> +  performInvokeReturn(call);
Already implemented :p

2021-07-27 17:57 UTC, Phantomical requested changes
I've left a few comments. A bigger issue is that it looks like you haven't fixed `longjmp` to work with invoke calls. I'm not sure why this doesn't give an error but it should work anyway. 
From my experiments caffeine just kills the context during the `longjmp` call.

Your test case for this doesn't actually use `invoke` for either `setjmp` or `longjmp`. Here's two test cases that should be enough to ensure that it's working.

## `run-fail/intrin/longjmp/invoke-longjmp.cpp`
```llvm
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }

; Here we use invoke to call both setjmp and longjmp
define dso_local void @test() local_unnamed_addr #0  
  personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*)
{
  %buf = alloca %struct.__jmp_buf_tag, align 16
  %res = invoke i32 @_setjmp(%struct.__jmp_buf_tag* nonnull %buf)
    to label %setjmp_normal unwind label %exception

setjmp_normal:
  switch i32 %res, label %failure [
    i32 0, label %setjmp_default
    i32 7, label %setjmp_landing
  ]

setjmp_default:
  invoke void @longjmp(%struct.__jmp_buf_tag* %buf, i32 7)
    to label %failure unwind label %exception

setjmp_landing:
  call void @caffeine_assert(i1 false)
  ret void

exception:
  %ex = landingpad { i8*, i32 } catch i8* null
  br label %failure

failure:
  ret void
}

declare dso_local void @caffeine_assume(i1 zeroext) local_unnamed_addr #1
declare dso_local void @caffeine_assert(i1 zeroext) local_unnamed_addr #1
declare dso_local i32 @_setjmp(%struct.__jmp_buf_tag*) local_unnamed_addr #2
declare dso_local void @longjmp(%struct.__jmp_buf_tag*, i32) local_unnamed_addr #3
declare dso_local i32 @__gxx_personality_v0(...)

attributes #0 = { nounwind uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { nounwind returns_twice }
attributes #3 = { noreturn nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.0-4ubuntu1 "}
```

## `run-pass/intrin/longjmp/invoke-longjmp.ll`
```llvm
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%struct.__jmp_buf_tag = type { [8 x i64], i32, %struct.__sigset_t }
%struct.__sigset_t = type { [16 x i64] }

; Here we use invoke to call both setjmp and longjmp
define dso_local void @test() local_unnamed_addr #0  
  personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*)
{
  %buf = alloca %struct.__jmp_buf_tag, align 16
  %res = invoke i32 @_setjmp(%struct.__jmp_buf_tag* nonnull %buf)
    to label %setjmp_normal unwind label %exception

  ; Dead block so that if we are just going to the next instruction then
  ; the test case fails.
dead_block:
  call void @caffeine_assert(i1 false)
  unreachable

setjmp_normal:
  switch i32 %res, label %failure [
    i32 0, label %setjmp_default
    i32 7, label %setjmp_landing
  ]

setjmp_default:
  invoke void @longjmp(%struct.__jmp_buf_tag* %buf, i32 7)
    to label %failure unwind label %exception

exception:
  %ex = landingpad { i8*, i32 } catch i8* null
  br label %failure

failure:
  call void @caffeine_assert(i1 false)
  unreachable

setjmp_landing:
  ret void
}

declare dso_local void @caffeine_assume(i1 zeroext) local_unnamed_addr #1
declare dso_local void @caffeine_assert(i1 zeroext) local_unnamed_addr #1
declare dso_local i32 @_setjmp(%struct.__jmp_buf_tag*) local_unnamed_addr #2
declare dso_local void @longjmp(%struct.__jmp_buf_tag*, i32) local_unnamed_addr #3
declare dso_local i32 @__gxx_personality_v0(...)

attributes #0 = { nounwind uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { nounwind returns_twice }
attributes #3 = { noreturn nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.0-4ubuntu1 "}
```

2021-07-27 17:57 UTC, Phantomical commented on src/Interpreter/Interpreter.cpp
Ok so my thought for this was something like this here
```suggestion
  if (func->empty()) {
    auto prev_bb = ctx->stack_top().current_block;
    auto res = visitExternFunc(callBase);

    auto invoke = llvm::dyn_cast<llvm::InvokeInst>(&callBase);
    if (!invoke)
      return res;

    if (res.empty()) {
      if (ctx->stack_top().current_block == prev_bb)
        performInvokeReturn(*ctx, invoke);
    } else {
      for (auto& ctx : res.contexts()) {
        if (ctx.stack_top().current_block == prev_bb)
          performInvokeReturn(ctx, invoke);
      }
    }
```
This way, we don't have to call `performInvokeReturn` for _every single external function_ and it will avoid doing things when the builtin function does bizarre things with control flow.

2021-07-27 17:57 UTC, Phantomical commented on src/Interpreter/Builtins/setjmp-longjmp.cpp
> +    }
If you use my suggested change above then you can avoid doing this dance altogether.

2021-07-27 17:57 UTC, Phantomical commented on src/Interpreter/Builtins/setjmp-longjmp.cpp
> +ExecutionResult Interpreter::visitLongjmp(llvm::CallBase& inst) {
You've accounted for `setjmp` being `invoke`d above but not for `longjmp` jumping to a `setjmp` call that was invoked.

2021-07-27 17:57 UTC, Phantomical commented on test/run-pass/intrin/longjmp/setjmp-longjmp.cpp
> +  longjmp(buf, 11);
Does this generate IR that calls invoke for `longjmp`?

2021-07-27 17:58 UTC, Phantomical commented on test/run-pass/intrin/longjmp/setjmp-longjmp.cpp
> +  longjmp(buf, 11);
Looked into this, it does not.

2021-07-29 19:08 UTC, Phantomical approved these changes
Can you clean up your debug logging? I've pointed out the places that should be cleaned up. Also, there's no need to skip tests that already pass even if they aren't working properly.

LGTM otherwise.

2021-07-29 19:08 UTC, Phantomical commented on src/Interpreter/Builtins/setjmp-longjmp.cpp
> +
Logging

2021-07-29 19:08 UTC, Phantomical commented on src/Interpreter/Builtins/setjmp-longjmp.cpp
> +      std::cout << "oh boy we're jumping back to an invoke" << std::endl;
Here

2021-07-29 19:08 UTC, Phantomical commented on src/Interpreter/Builtins/setjmp-longjmp.cpp
> +  return res;
Here

2021-07-29 19:08 UTC, Phantomical commented on test/run-pass/intrin/longjmp/setjmp-longjmp.c
> +// SKIP TEST
This doesn't need to be skipped since it already passes on master (even though it doesn't work).

2021-07-29 19:21 UTC, merged