Serializer class and serializer protos
insufficiently-caffeinated/caffeine pull request #482
Opened 2021-07-28 21:29 UTC by brookedolny

2021-07-28 21:30 UTC, brookedolny commented on src/Protos/solver.capnp
> +using Cxx = import "/capnp/c++.capnp";
Originally I was going to have the protos here but I ended up adding a separate proto folder in the serializer tool

2021-07-28 21:31 UTC, brookedolny commented on tools/test-serializer/CMakeLists.txt
> +message(STATUS "includes: ${includes}")
I'm removing these I just forgot to before I pushed

2021-07-28 21:33 UTC, brookedolny commented on tools/test-serializer/src/Serializer.cpp
> +        const byte * b = reinterpret_cast<const unsigned char *>(symbols[i].bytes);
`byte` is defined as an `unsigned char`

2021-07-28 21:34 UTC, brookedolny commented on tools/test-serializer/include/Serializer.h
> +class Serializer {
Feedback on structure is welcomed

2021-07-28 21:34 UTC, brookedolny commented on tools/test-serializer/include/Serializer.h
> +class Serializer {
Like please someone look at this lol

2021-07-28 22:22 UTC, Phantomical requested changes
Overall I think you have the right idea here :). The prototype design looks pretty good to me and the actual conversion to the capnproto types seems to be good.

With that said I think there's some design/organization issues here. I'll list these out along with my suggestions for fixing them. However, if you think you've got a better approach then feel free to do whatever you think is best.
- First off, this code is not usable from the `caffeine` library. My suggestion is that you move this back into the main library (I realize I said something else when initially coming up with the issue) and then later on _in a different PR_ we can export that subset of the source as library that can be used on its own.
- Second, the `Serializer` class has a bunch of responsibilities that would make it rather difficult to use.
  1. It always writes to a file and it opens that file internally. This means that we can't write the output to anything other than a file (e.g. a database or as part of a larger file format).
  2. It has a whole bunch of responsibilities and it's trying to do too much.
  
  My suggestion here is that you simplify the API to only serialization/deserialization - something that looks like this
  ```cpp
  std::vector<char> serialize_test_case(const std::unordered_map<std::string, std::string>);
  std::unordered_map<std::string, std::string> deserialize_test_case(std::string_view data);
  ```
  so that the users of this code can write the data to wherever they want. Note that `std::string` is fine containing nul chars as long as you construct it using the ptr + size ctor.
  
Basically, my suggestions here are to move stuff back into the caffeine library (under `Serialization`) and simplify the API to the minimum required. Then in a follow up PR we can export just that bit as a library that can be used for a `libcaffeinert` library that allows for running with a concrete test case.

2021-07-28 22:22 UTC, Phantomical commented on tools/test-serializer/Protos/testcase.capnp
> +@0xa5a2c19ddf8b8759;
This file seems out-of-date.

2021-07-28 22:22 UTC, Phantomical commented on tools/test-serializer/src/Serializer.cpp
> +    int fd = fileno(file);
Note that `fileno` is not part of standard C. It is part of POSIX and won't work on windows.

2021-08-13 18:52 UTC, brookedolny commented on tools/test-serializer/include/Serializer.h
> +    void load_test_case(int fd);
Done (used VectorOutputStream and ArrayInputStream for the inverse)

2021-08-13 18:52 UTC, brookedolny commented on tools/test-serializer/include/Serializer.h
> +class Serializer {
No more classes :)

2021-08-13 18:53 UTC, brookedolny commented on tools/test-serializer/Protos/testcase.capnp
> +    empty @0 :Void;
This was used mainly because a union must have at least 2 fields and I didn't have another

2021-08-13 18:53 UTC, brookedolny commented on tools/test-serializer/Protos/testcase.capnp
> +}
Deleted

2021-08-13 18:53 UTC, brookedolny commented on tools/test-serializer/src/Serializer.cpp
> +    int fd = fileno(file);
Removed

2021-08-13 19:31 UTC, brookedolny commented
Okay, I've updated the Serialize functionality to live in the Serialization folder in Caffeine, and it's just two function calls:

```
std::vector<char> serialize_test_case(const std::unordered_map<std::string, std::string>);
std::unordered_map<std::string, std::string> deserialize_test_case(std::vector<char> data);
```

2021-08-17 00:29 UTC, Phantomical commented
@brookedolny I think you said this is ready for review so I've moved it out of draft.

2021-08-17 00:35 UTC, Phantomical approved these changes
I've got one small nit WRT to API and another formatting suggestion but otherwise LGTM!

2021-08-17 00:35 UTC, Phantomical commented on include/caffeine/Serialization/Serialize.h
> +namespace serialize {
You can use a compound namespace declaration to avoid having to indent what's inside.
```suggestion
namespace caffeine::serialize {
```

2021-08-17 00:35 UTC, Phantomical commented on include/caffeine/Serialization/Serialize.h
> +  deserialize_test_case(std::vector<char>& data);
I suggest using `std::string_view` for `data` here.  `std::vector<char>` is generally somewhat awkward to use.

2021-08-17 00:35 UTC, Phantomical commented on include/caffeine/Serialization/Serialize.h
> +  deserialize_test_case(std::vector<char>& data);
I suggest using `std::string_view` for `data` here.  `std::vector<char>` is generally somewhat awkward to use.

2021-08-21 03:36 UTC, brookedolny commented on include/caffeine/Serialization/Serialize.h
> +  deserialize_test_case(std::vector<char>& data);
`std::vector<char>` is used here so that `deserialize_test_case` is the inverse of `serialize_test_case`. Using `std::string` (or `std::string_view`) implies the data is text instead of raw (serialized) byte data which has to be processed.

2021-08-21 03:36 UTC, brookedolny commented on include/caffeine/Serialization/Serialize.h
> +namespace serialize {
I forgot I could do that, thanks

2021-10-21 00:32 UTC, merged