Implement coroutines and add an example implementation
insufficiently-caffeinated/caffeine pull request #541
Opened 2021-11-10 03:43 UTC by mishazharov

This PR implements more functionality in `ExternalStackFrame`s up to a point where it's possible to implement external functions using the `ExternalStackFrame`. The `ExternalStackFrame` will be used in order to keep state of external functions which can fork, call other functions, and return results.

Example implementation via `CaffeineAssert`.

2021-11-12 04:17 UTC, Phantomical requested changes
I've got a bunch of small nits on how things are done along with some bigger concerns about values that don't do anything in `ExternalStackFrame`.

2021-11-12 04:17 UTC, Phantomical commented on src/Interpreter/Interpreter.cpp
> +    return ExecutionResult::Continue;
This should be returning `ExecutionResult::Migrated` if it's using `InterpreterContext` to manage forking.

2021-11-12 04:17 UTC, Phantomical commented on src/Interpreter/Interpreter.cpp
> +    std::vector<LLVMValue> args;
Could we keep this all within `visitAssert` for now? It will eventually get cleaned up but I don't think it helps to make `visitExternFunc` bigger at the moment.

2021-11-12 04:17 UTC, Phantomical commented on src/Interpreter/Interpreter.cpp
> +    interp->context().stack.push_back(StackFrame(std::move(frame)));
This should probably be a helper within `InterpreterContext` somewhere since it will be used in a bunch of places.

2021-11-12 04:17 UTC, Phantomical commented on include/caffeine/Interpreter/StackFrame.h
> +  uint64_t program_counter = 0;
What is this used for?

The actual implementation of how any individual external stack frame figures out what state is in shouldn't be the responsibility of the parent class (they may not use an integer).

2021-11-12 04:17 UTC, Phantomical commented on include/caffeine/Interpreter/StackFrame.h
> +                     llvm::Function* func = nullptr);
This should probably not be defaulted? A null function is always invalid.

2021-11-12 06:35 UTC, mishazharov commented on include/caffeine/Interpreter/StackFrame.h
> +                     llvm::Function* func = nullptr);
Removed the default but it's actually not invalid to have a null function because an `ExternalFunction` declared in a module can call an `ExternalFunction` that's not declared in a module (which would lead to the null pointer)

2021-11-12 07:51 UTC, Phantomical approved these changes
One last nit but otherwise LGTM

2021-11-12 07:51 UTC, Phantomical commented on include/caffeine/Interpreter/InterpreterContext.h
> +  void call_external_function(std::unique_ptr<ExternalStackFrame>&& frame);
Can you add some docs explaining what this does?

2021-11-16 04:32 UTC, mishazharov commented on include/caffeine/Interpreter/InterpreterContext.h
> +  void call_external_function(std::unique_ptr<ExternalStackFrame>&& frame);
:p yep, good call

2021-11-16 04:45 UTC, merged