Linecov
insufficiently-caffeinated/caffeine pull request #553
Opened 2021-11-26 05:16 UTC by Skrinikov

Adds Line coverage tracking.

The basic idea right now is to just count how many times a line has been hit. 

Later I want to also add global coverage tracking (e.g. how many times total passthroughs we did to generate percentage statistics)

This PR is still wip, but I mark it as ready to get github compiler support

2021-12-01 03:19 UTC, Phantomical reviewed
You've got some formatting problems left and I've left some nits. Lmk if you want me to give it another review :)

You can fix the formatting by either `make format` or `bazel run :format`. Both should (hopefully) be fairly fast.

2021-12-01 03:19 UTC, Phantomical commented on include/caffeine/Support/Coverage.h
> +    // CoverageTracker operator=(CoverageTracker&&) = default;
You can probably just delete this - it's probably not necessary unless you've got some mix of defaulted and deleted constructors.

I would keep the `CoverageTracker() = default` though since that ensures that the default constructor sticks around even if you add others.

2021-12-01 03:19 UTC, Phantomical commented on include/caffeine/Support/Coverage.h
> +    // Line operator=(Line&&) = default;
Same comment here WRT defaulted ctors/dtors.

2021-12-01 03:19 UTC, Phantomical commented on include/caffeine/Support/Coverage.h
> +    size_t Hits() const;
Nit: these should be either camelCase or snake_case.

2021-12-01 03:19 UTC, Phantomical commented on include/caffeine/Support/Coverage.h
> +    void touch(std::string filename, size_t line);
This should either be `std::string_view`, `const std::string&`, or `llvm::StringRef` depending on whatever is convenient.

2021-12-01 03:19 UTC, Phantomical commented on tools/caffeine/main.cpp
> +                      .with_coverage(cov)
```suggestion
                      .with_coverage(CoverageTracker())
```

2021-12-03 01:34 UTC, Skrinikov commented on include/caffeine/Support/Coverage.h
> +    std::map<std::string, size_t> file_to_vec;
Unordered map may be useful if we decide to make the reporting smarter but as an initial implementation I will switch to `StringMap`

2021-12-03 04:05 UTC, Phantomical commented on include/caffeine/Support/Coverage.h
> +    std::map<std::string, size_t> file_to_vec;
Note that `StringMap` is just a more efficient `std::unordered_map` that gives slightly better ergonomics.

2021-12-18 18:47 UTC, Phantomical requested changes
If I approve then this will automatically merge so I'm going to request a few small changes and then I'll approve once you've had a chance to make them. However, other than a few small things the PR LGTM!

One last thing: could you make a command-line option that enables/disables coverage tracking + printing?

2021-12-18 18:47 UTC, Phantomical commented on src/Interpreter/Interpreter.cpp
> +  }
Instead of an option here you could also check whether the context has an instance of the coverage tracker
```suggestion
  if (interp->caffeine().coverage()) {
    getInstLine(inst);
  }
```

2021-12-18 18:47 UTC, Phantomical commented on src/Interpreter/CaffeineContext.cpp
> +  return nullptr;
This can just be
```suggestion
  return cov_.get();
```

2021-12-18 19:34 UTC, Phantomical reviewed
Realized I forgot to do this so I'm leaving the full set of changes WRT to just deciding whether to emit coverage info if there's a coverage tracker in the context.

2021-12-18 19:34 UTC, Phantomical commented on include/caffeine/Interpreter/CaffeineContext.h
> +
Remove this since whether or not a tracker is present communicates the same information.

2021-12-18 19:34 UTC, Phantomical commented on src/Interpreter/CaffeineContext.cpp
> +        "No coverage tracker provided when building CaffeineContext");
This can also be removed since we're deleting `run_line_coverage`

2021-12-18 19:34 UTC, Phantomical commented on tools/caffeine/main.cpp
> +  std::unique_ptr<CoverageTracker> cov = std::make_unique<CoverageTracker>();
Whether this is constructed or not should be decided by a command-line option. So something like
```cpp
std::unique_ptr<CoverageTracker> cov = nullptr;
if (coverage_enabled)
  cov = std::make_unique<CoverageTracker>();
```

2021-12-18 19:34 UTC, Phantomical commented on tools/caffeine/main.cpp
> +  if (caffeine.options().run_line_coverage) {
```suggestion
  if (caffeine.coverage()) {
```

2021-12-19 04:29 UTC, Phantomical approved these changes
LGTM!

2021-12-19 04:29 UTC, merged